import { IMG } from "./images";

export type Category = "Vendre à Toulouse" | "Acheter autrement" | "Le marché en clair" | "Vendre / Acheter";

export type Block =
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "quote"; text: string };

export interface Article {
  slug: string;
  title: string;
  cat: Category;
  excerpt: string;
  img: string;
  imgPos?: string;
  date: string; // ISO
  readingTime: number; // minutes
  blocks: Block[];
  cta: string;
}

export const ARTICLES: Article[] = [
  {
    slug: "pourquoi-je-travaille-en-exclusivite",
    title: "Pourquoi je travaille en exclusivité - et ce que cela change pour vous",
    cat: "Vendre à Toulouse",
    excerpt:
      "L'exclusivité n'est pas une contrainte : c'est ce qui rend la vente lisible et efficace.",
    img: IMG.blogSignature,
    imgPos: "object-center",
    date: "2026-05-02",
    readingTime: 5,
    blocks: [
      { type: "quote", text: "Une exclusivité pour mieux t'en occuper ? Pourquoi, tu t'en occupes moins quand il y a plusieurs agences ?" },
      { type: "p", text: "C'est une question qu'on m'a posée directement, avec un sourire légèrement ironique. Elle est honnête. Elle mérite une réponse honnête." },
      { type: "h3", text: "Ce que la multi-agence produit vraiment" },
      { type: "p", text: "Imaginez votre appartement affiché sur trois, quatre portails différents. Trois agences, trois prix parfois légèrement différents, trois annonces avec des photos inégales. Un acheteur sérieux qui cherche depuis plusieurs semaines va le voir. Puis le revoir. Puis se demander pourquoi il est toujours là." },
      { type: "p", text: "Plus un bien est visible partout, plus longtemps il reste sans offre, et le doute s'installe. Or dans l'immobilier, quand il y a un doute, il n'y a plus de doute : les acheteurs concluent qu'il y a un loup. Ils passent au suivant." },
      { type: "p", text: "La multi-agence crée un paradoxe : en voulant maximiser l'exposition, on finit par fragiliser la valeur du bien." },
      { type: "h3", text: "Ce que l'exclusivité change concrètement" },
      { type: "p", text: "Quand je travaille en exclusivité, je suis la seule à publier votre bien. Une annonce, soignée, avec des photos cohérentes et un prix unique. Le message envoyé au marché est clair : ce bien est suivi, défendu, présenté sérieusement." },
      { type: "p", text: "Mais l'exclusivité ne signifie pas que je travaille seule." },
      { type: "p", text: "Je partage systématiquement avec mes confrères et consœurs - toutes agences et mandataires confondus. Si un agent a l'acheteur qu'il vous faut dans son portefeuille, votre bien lui est accessible. Vous bénéficiez donc d'un réseau large, sans la dispersion visuelle que produit la multi-agence." },
      { type: "p", text: "Et ce partage ne vous coûte pas un euro de plus. Les honoraires sont partagés entre nous. Vous payez ce qui était prévu, rien d'autre." },
      { type: "h3", text: "Pourquoi je m'y engage plus, pas moins" },
      { type: "p", text: "L'objection du début de cet article repose sur une logique compréhensible : plusieurs agents, plus de chances. Mais en pratique, quand plusieurs agences ont un mandat sur le même bien, chacune sait que les autres travaillent aussi dessus. L'urgence diminue. Les efforts se répartissent, ou plutôt, chacun attend de voir si un autre conclut d'abord." },
      { type: "p", text: "Avec un mandat exclusif, c'est différent. Je suis la seule responsable du résultat. Je prépare l'estimation avec soin, j'organise les visites, je sélectionne les acquéreurs avant de vous faire perdre du temps, je négocie, je suis le dossier jusqu'à la signature chez le notaire." },
      { type: "p", text: "Mon expérience bancaire me permet d'aller plus loin que la visite : je sais reconnaître un acquéreur dont le dossier tient la route. Vous ne recevez pas dix visites pour aboutir à trois désistements pour refus de prêt. Vous recevez les bons acheteurs." },
      { type: "h3", text: "Ce que l'exclusivité dit de votre bien" },
      { type: "p", text: "Confier un bien en exclusivité, c'est aussi envoyer un signal fort au marché : vous avez confiance dans la démarche, dans le prix, dans l'agent que vous avez choisi. Ce signal compte. Les acheteurs sérieux le lisent." },
      { type: "p", text: "Un bien en exclusivité bien positionné se vend. C'est aussi simple que ça." },
    ],
    cta: "Vous souhaitez qu'on en parle pour votre projet ? Je reste à votre écoute.",
  },
  {
    slug: "ce-que-votre-banquier-regardera",
    title: "Ce que votre banquier regardera dans votre dossier",
    cat: "Acheter autrement",
    excerpt: "Capacité, charges, reste à vivre : ce qui se joue avant même la première visite.",
    img: IMG.blogHero,
    imgPos: "object-bottom",
    date: "2026-04-25",
    readingTime: 6,
    blocks: [
      { type: "p", text: "On parle beaucoup de budget quand on cherche un bien. Beaucoup moins de ce que le banquier va réellement regarder quand il ouvrira votre dossier. C'est pourtant là que beaucoup de projets d'achat se bloquent - parfois à quelques semaines de la signature." },
      { type: "p", text: "Mon passage en banque m'a appris une chose : ce que les gens croient préparer et ce que le banquier examine ne sont pas toujours la même chose." },
      { type: "h3", text: "L'enveloppe d'abord - vraiment" },
      { type: "p", text: "Avant la première visite, je m'assure que vous avez fait calculer votre enveloppe de financement. Pas une estimation approximative faite mentalement un dimanche soir, une enveloppe réelle, posée avec un courtier ou un banquier, qui tient compte de votre situation au moment où vous cherchez." },
      { type: "p", text: "C'est la base. Sans elle, vous visitez dans le vide. Vous vous attachez à des biens hors de portée, ou vous passez à côté de biens accessibles parce que vous vous êtes fixé une limite trop basse. Le calcul d'enveloppe n'est pas une formalité administrative - c'est ce qui rend votre recherche efficace." },
      { type: "h3", text: "Les trois derniers mois de relevés de compte" },
      { type: "p", text: "C'est là que beaucoup de dossiers se fragilisent sans que les acheteurs le voient venir." },
      { type: "p", text: "Le banquier va demander vos trois derniers relevés de compte. Il ne cherche pas à vous juger - il cherche à comprendre si vos habitudes financières sont compatibles avec un remboursement mensuel stable sur vingt ans. Ce qu'il regarde concrètement : des dépenses identifiables, régulières, qui signalent une gestion saine. Et ce qui l'inquiète : des mouvements inhabituels, des découverts répétés, des dépenses ponctuelles importantes dans les semaines qui précèdent la demande." },
      { type: "p", text: "Ce n'est pas une question de montant. C'est une question de lisibilité. Un dossier lisible rassure. Un dossier brouillon, même avec de bons revenus, crée du doute." },
      { type: "p", text: "Mon conseil est simple : dans les trois mois qui précèdent votre demande de prêt, évitez les dépenses inhabituelles identifiables sur votre compte. Pas d'achat de voiture à crédit, pas de voyage réglé en plusieurs fois, pas de découvert même ponctuel. Rien qui puisse faire tiquer." },
      { type: "h3", text: "L'apport et la mensualité idéale - deux notions à ne pas confondre" },
      { type: "p", text: "L'apport rassure le prêteur. Il montre une capacité à épargner, une gestion saine dans le temps. En général, les banques demandent a minima de couvrir les frais de notaire - autour de 7 à 8% du prix pour un bien ancien. Au-delà, chaque euro d'apport supplémentaire améliore les conditions du prêt et renforce votre dossier. Si vous en avez la possibilité, ne le gardez pas en réserve par réflexe - il travaille mieux dans le dossier." },
      { type: "p", text: "Mais l'apport n'est qu'une partie de l'équation. L'autre, qu'on aborde moins souvent, c'est la mensualité idéale - pas la mensualité maximale finançable." },
      { type: "p", text: "La banque va calculer ce qu'elle peut vous prêter selon vos revenus et votre taux d'endettement. Ce montant peut être élevé. La vraie question est : est-ce que vous voulez y consacrer autant chaque mois ? Un projet immobilier réussi, c'est un projet qui laisse de la place pour le reste - les imprévus, les vacances, les projets de vie qui ne s'arrêtent pas le jour de la signature." },
      { type: "p", text: "Je préfère qu'on parte d'une mensualité avec laquelle vous dormez bien, plutôt que de la mensualité maximale que le banquier accepte de financer. Ce n'est pas la même chose, et la différence se ressent pendant vingt ans." },
      { type: "h3", text: "Pourquoi je travaille avec un courtier" },
      { type: "p", text: "Je ne fais pas le travail du banquier, et je ne remplace pas le courtier. Mais je travaille régulièrement avec des courtiers pour m'assurer que le financement de mes acheteurs tient la route avant qu'on aille plus loin." },
      { type: "p", text: "Un courtier connaît les critères réels de chaque établissement bancaire au moment où vous cherchez. Il sait qui finance quel profil, à quel taux, avec quelles conditions. Il négocie à votre place. Et surtout, il évite les refus - parce qu'un refus de prêt, c'est un compromis qui tombe, un vendeur déçu, et un acheteur qui repart de zéro." },
      { type: "p", text: "Vous présenter à un vendeur avec un dossier solide et un courtier dans la boucle, c'est aussi une façon de vous démarquer. Dans un marché tendu, un acheteur bien préparé est un acheteur crédible." },
      { type: "h3", text: "Ce que je vérifie avant qu'on visite ensemble" },
      { type: "p", text: "Quand un acheteur me contacte, je prends le temps d'un premier échange sur sa situation avant d'organiser des visites. Enveloppe calculée, relevés en ordre, apport disponible, situation professionnelle stable - je veux m'assurer que le projet est solide avant de le lancer." },
      { type: "p", text: "Ce n'est pas de la méfiance. C'est du respect de votre temps - et de celui du vendeur." },
    ],
    cta: "Votre projet d'achat prend forme ? Je reste à votre écoute.",
  },
  {
    slug: "honoraires-trop-eleves",
    title: "Ce que j'entends quand on me dit que mes honoraires sont trop élevés",
    cat: "Vendre à Toulouse",
    excerpt: "Une réponse simple, sans détour, à une objection que j'entends souvent.",
    img: IMG.altMeilleur,
    date: "2026-04-18",
    readingTime: 5,
    blocks: [
      { type: "p", text: "C'est une phrase que j'entends. Pas toujours formulée aussi directement, parfois glissée entre deux questions, parfois posée franchement en fin de rendez-vous. Je la comprends. Un pourcentage appliqué sur un prix de vente, ça représente une somme réelle, et il est normal de se demander ce qu'on en a pour son argent." },
      { type: "p", text: "Voici ce que je réponds." },
      { type: "h3", text: "Ce que les honoraires financent vraiment" },
      { type: "p", text: "Quand vous signez un mandat avec moi, vous ne payez pas une annonce sur SeLoger. Vous payez une prise en charge complète du processus de vente - de l'estimation jusqu'à la signature chez le notaire." },
      { type: "p", text: "Concrètement : la préparation de votre bien, les photos, la rédaction de l'annonce, la sélection des acquéreurs avant même la première visite, l'organisation des visites, la négociation, le suivi du dossier de financement, la coordination avec le notaire. Tout ce que vous n'avez pas à gérer, à relancer, à surveiller." },
      { type: "p", text: "Pour quelqu'un de débordé ou qui traverse une période chargée, cette tranquillité a une valeur réelle. Elle n'est pas toujours facile à chiffrer avant de l'avoir vécue. Après, elle l'est." },
      { type: "h3", text: "Ce que mes honoraires permettent en plus" },
      { type: "p", text: "Mes honoraires incluent la possibilité de partager avec des confrères et consœurs - toutes agences et mandataires confondus. Si un agent a l'acheteur qu'il vous faut, votre bien lui est accessible." },
      { type: "p", text: "Ce partage ne vous coûte pas un euro supplémentaire. Les honoraires sont répartis entre nous. Ce que vous payez ouvre un réseau, pas une seule vitrine." },
      { type: "p", text: "Un mandat à honoraires réduits, c'est souvent un mandat qui ne peut pas être partagé. L'agent ne peut pas céder la moitié d'une commission déjà comprimée. Votre bien reste dans un seul portefeuille. Ce n'est pas nécessairement un problème - mais c'est une réalité à connaître avant de choisir." },
      { type: "h3", text: "La vraie question n'est pas le montant, c'est le net vendeur" },
      { type: "p", text: "Quand on parle d'honoraires, on parle en réalité de net vendeur - ce que vous touchez vraiment à la fin, après les frais d'agence et les frais de notaire." },
      { type: "p", text: "Un bien vendu vite, au bon prix, avec un acheteur dont le dossier tient, produit un meilleur net vendeur qu'un bien qui traîne six mois, se déprécie dans l'esprit du marché, et finit par partir en dessous du prix initial." },
      { type: "p", text: "Mon expérience bancaire me permet de sélectionner des acquéreurs sérieux - ceux dont le financement est solide, ceux qui ne vont pas se rétracter trois semaines avant la signature pour un refus de prêt. Vous ne perdez pas de temps en visites inutiles. Vous ne perdez pas de valeur en restant trop longtemps sur le marché." },
      { type: "p", text: "C'est ça, le vrai calcul." },
      { type: "h3", text: "Ce que je ne dis pas" },
      { type: "p", text: "Je ne dis pas que mes honoraires sont les plus bas du marché. Je ne le prétends pas et ce n'est pas mon positionnement." },
      { type: "p", text: "Ce que je dis : pour un vendeur qui veut vendre au bon prix, dans un délai raisonnable, sans gérer seul les aléas du processus, le coût réel d'un bon accompagnement est souvent inférieur au coût d'un mauvais." },
    ],
    cta: "Vous avez un projet de vente et des questions sur mes honoraires ? Je reste à votre écoute - une conversation suffit souvent à clarifier les choses.",
  },
  {
    slug: "avant-de-visiter-le-premier-appartement",
    title: "Avant de visiter le premier appartement, voici ce que je vérifie",
    cat: "Acheter autrement",
    excerpt: "Une checklist concrète pour structurer un projet d'achat avant de perdre du temps.",
    img: IMG.blogAppartement,
    date: "2026-04-10",
    readingTime: 5,
    blocks: [
      { type: "p", text: "On pourrait croire que mon travail commence à la visite. En réalité, il commence bien avant. Parce qu'une visite mal préparée fait perdre du temps à tout le monde - à l'acheteur, au vendeur, et à moi." },
      { type: "p", text: "Voici ce que je vérifie systématiquement avant qu'on franchisse une porte ensemble." },
      { type: "h3", text: "Le quartier d'abord" },
      { type: "p", text: "Un bien ne s'achète pas seul. Il s'achète avec son environnement immédiat, et cet environnement va faire partie de votre quotidien pendant des années." },
      { type: "p", text: "Avant toute visite, je regarde le quartier avec vos critères en tête. Pas les miens - les vôtres. Les transports dont vous avez besoin, les commerces que vous fréquentez, les écoles si c'est un sujet, la nature du voisinage. Je marche dans la rue si je ne la connais pas déjà. Je regarde ce qui se passe en journée, ce que révèle Google Maps en dehors des photos soignées de l'annonce." },
      { type: "p", text: "Toulouse est une ville de quartiers, et deux rues peuvent faire une différence réelle en termes d'ambiance, de prix, et de valeur future. Ces nuances, je les connais parce que je travaille ce marché depuis quatre ans." },
      { type: "p", text: "Un quartier qui ne correspond pas à votre mode de vie, aucune rénovation ne le changera." },
      { type: "h3", text: "La surface et ce qu'elle cache" },
      { type: "p", text: "La surface affichée dans une annonce est rarement la surface que vous habitez vraiment." },
      { type: "p", text: "Je vérifie la surface loi Carrez pour les appartements - c'est la surface légale, celle qui engage le vendeur. Mais je regarde aussi la distribution des pièces : est-ce que les volumes sont bien utilisés ? Est-ce qu'il y a des espaces perdus, des couloirs surdimensionnés, une pièce aveugle ? Un 65 m² bien distribué se vit mieux qu'un 72 m² mal pensé." },
      { type: "p", text: "Je regarde aussi l'orientation. Un appartement plein nord à Toulouse, même bien rénové, restera sombre en hiver. L'exposition conditionne le confort thermique, la luminosité, et indirectement les charges de chauffage. C'est un critère qui ne se voit pas sur les photos - souvent prises par beau temps, en grand angle." },
      { type: "h3", text: "Les prestations - ce qui est visible et ce qui ne l'est pas" },
      { type: "p", text: "Les prestations, c'est ce que le bien offre au-delà des murs : le standing de la résidence, l'état des parties communes, la présence d'un ascenseur, d'un parking, d'une cave, d'un extérieur. Ce sont des éléments qui influencent directement la valeur et la facilité de revente future." },
      { type: "p", text: "Mais je regarde aussi ce qui ne se voit pas immédiatement. L'état du syndic et des charges de copropriété - des charges élevées ou mal gérées peuvent significativement alourdir le coût réel du bien. Les procès-verbaux des dernières assemblées générales, qui révèlent les travaux votés ou à venir. Le DPE, qui conditionne désormais la valeur locative et la facilité de financement dans certains cas." },
      { type: "p", text: "Mon passage en banque m'a appris à lire une situation financière globale. Je regarde un bien comme je regardais un dossier : en cherchant ce qui est visible, et ce qui mérite d'être creusé." },
      { type: "h3", text: "Ce que tout cela change pour vous" },
      { type: "p", text: "Préparer une visite sérieusement, c'est vous éviter de tomber amoureux d'un bien qui ne correspond pas à vos critères réels. C'est aussi vous permettre de vous projeter avec lucidité sur les biens qui correspondent vraiment." },
      { type: "p", text: "Je ne visite pas pour visiter. Je visite pour avancer." },
    ],
    cta: "Votre projet d'achat prend forme ? Je reste à votre écoute.",
  },
  {
    slug: "marche-toulousain-2026",
    title: "Le marché toulousain en 2026 : ce que les chiffres disent vraiment",
    cat: "Le marché en clair",
    excerpt: "Bilan annuel, données DVF commentées, lecture sans bullshit.",
    img: IMG.blogToits,
    date: "2026-04-03",
    readingTime: 7,
    blocks: [
      { type: "p", text: "Toulouse est souvent présentée comme un marché dynamique, attractif, en croissance. C'est vrai dans les grandes lignes. Mais les grandes lignes ne suffisent pas quand on décide de vendre ou d'acheter. Ce qui compte, ce sont les chiffres réels, lus avec un peu de recul." },
      { type: "p", text: "Voici ce que le marché toulousain dit vraiment en 2026." },
      { type: "h3", text: "Les prix : une stabilisation après plusieurs années de hausse" },
      { type: "p", text: "En 2025, le prix moyen des appartements anciens à Toulouse s'est stabilisé autour de 3 600 à 3 800 €/m², selon les notaires et les portails spécialisés. Après plusieurs années de hausse continue, la courbe s'est enfin infléchie. Le marché immobilier toulousain entre dans une phase plus équilibrée. Les tarifs se stabilisent, les écarts entre biens deviennent plus visibles et chaque projet mérite une analyse précise." },
      { type: "p", text: "Ce que cela signifie concrètement : le temps où un bien mal estimé se vendait quand même parce que le marché portait tout est révolu. Un bien correctement positionné se vend. Un bien surestimé reste. La précision de l'estimation est redevenue un facteur déterminant." },
      { type: "h3", text: "Les transactions : une reprise réelle mais sélective" },
      { type: "p", text: "Après une hausse notable des transactions en 2025, le volume atteint des niveaux proches de 16 000 ventes annuelles dans l'agglomération, avec une projection prudente autour de +5% pour 2026. En 2024, 6 713 transactions ont été réalisées à Toulouse, dont 85% d'appartements et 15% de maisons." },
      { type: "p", text: "Le marché tourne, mais pas uniformément. Les biens bien présentés se vendent vite avec une marge de négociation limitée. Le délai de vente moyen varie fortement : 20 à 40 jours pour les biens bien positionnés, 2 à 4 mois pour les biens à rénover." },
      { type: "p", text: "C'est précisément là que l'estimation juste et la préparation du bien font toute la différence." },
      { type: "h3", text: "Les taux : stables, mais exigeants" },
      { type: "p", text: "Après la forte hausse de 2022-2023 et la détente progressive de 2024, les taux se stabilisent en 2026 à un niveau qui reste significatif. En mai 2026, le taux moyen s'établit à 3,26% sur 20 ans et 3,38% sur 25 ans pour les meilleurs profils. Les primo-accédants demeurent le moteur du marché - ils représentaient 52% des nouveaux crédits accordés en 2025, selon la Banque de France." },
      { type: "p", text: "Ce contexte a deux conséquences directes. Pour les vendeurs : les acheteurs sont plus sélectifs, leur capacité d'emprunt est encadrée, et les dossiers de financement sont scrutés de près. Pour les acheteurs : la préparation du dossier bancaire en amont n'est pas une option, c'est une condition de réussite." },
      { type: "h3", text: "Les prix selon les secteurs : Toulouse n'est pas un marché uniforme" },
      { type: "p", text: "Le prix moyen des appartements se situe entre 3 100 € et 4 500 €/m² selon le quartier, mais cette fourchette masque des réalités très différentes. Toulouse se lit en micro-marchés, et deux rues peuvent faire une différence significative en termes de valeur, de profil d'acheteur et de délai de vente." },
      { type: "p", text: "Les quartiers les plus côtés concentrent une demande soutenue et des prix élevés, portés par leur prestige historique, leur qualité de vie et un profil d'acheteurs CSP+ qui ne faiblit pas. Ce sont des secteurs où les biens partent vite quand ils sont bien estimés, et où la marge de négociation reste limitée." },
      { type: "p", text: "Certains quartiers se sont progressivement boboisés, portés par une demande nouvelle, des projets urbains et une vie de quartier qui se densifie. Leur cote monte. Ce sont des secteurs qui offrent encore un rapport qualité-prix intéressant par rapport aux quartiers les plus prisés, mais dont les prix rattrapent progressivement." },
      { type: "p", text: "Pour un primo-accédant avec un budget contraint, la stratégie dépend avant tout du profil. Un acheteur citadin, habitué au métro et au bus, va chercher la proximité d'une station de métro, des commerces à pied, une vie de quartier animée - et accepte de s'éloigner du centre si ces critères sont réunis. Un acheteur autonome en voiture va raisonner différemment : accès rapide à la rocade, gare à proximité, place de parking. Ce sont ces critères concrets, plus que le nom du quartier, qui sécurisent à la fois le quotidien et la revente." },
      { type: "h3", text: "Ce que j'en retiens pour mes clients" },
      { type: "p", text: "Un marché qui se stabilise n'est pas un marché qui s'arrête. C'est un marché qui devient plus lisible - et qui récompense ceux qui s'y préparent sérieusement." },
      { type: "p", text: "Pour un vendeur : l'estimation au prix juste est redevenue la clé. Un bien surestimé de 5% ne se vend plus en négociant - il stagne, se déprécie dans l'esprit du marché, et finit souvent par partir en dessous de ce qu'une estimation correcte aurait permis d'obtenir dès le départ." },
      { type: "p", text: "Pour un acheteur : les opportunités existent, notamment sur les biens à rafraîchir et dans les secteurs en développement. Mais elles ne restent pas longtemps disponibles quand le dossier est solide et le projet structuré." },
    ],
    cta: "Vous voulez savoir où se situe votre bien dans ce marché ? Je reste à votre écoute.",
  },
  {
    slug: "vente-t3-patte-doie",
    title: "Une vente, une histoire : le T3 de la Patte d'Oie",
    cat: "Vendre à Toulouse",
    excerpt: "Quatre mois de visites, deux frères, une vision. Ce qu'une vente atypique m'a appris.",
    img: IMG.blogQuartier,
    date: "2026-03-27",
    readingTime: 5,
    blocks: [
      { type: "p", text: "Il y a des ventes qui se concluent vite. Et il y a celles qui vous apprennent quelque chose." },
      { type: "p", text: "Celle-là, je m'en souviens bien." },
      { type: "h3", text: "Le bien" },
      { type: "p", text: "Un T3 au troisième étage, sans ascenseur, dans le quartier de la Patte d'Oie. Pas de travaux de rafraîchissement - une rénovation complète à prévoir. Le genre de bien qui demande de se projeter au-delà de ce qu'on voit, et ils étaient peu à le faire." },
      { type: "p", text: "Le quartier, lui, ne posait pas de problème. La Patte d'Oie a sa cote, son ambiance, sa vie. Mais l'étage sans ascenseur et l'état du bien filtraient naturellement les candidats." },
      { type: "h3", text: "Quatre mois et des visites qui ne menaient nulle part" },
      { type: "p", text: "Pendant quatre mois, les acquéreurs potentiels se sont succédé. Certains sont venus une fois et n'ont pas rappelé. D'autres ont visité, réfléchi, et se sont découragés au moment d'estimer les travaux. Le bien était correct dans sa configuration, honnête dans son prix - mais personne ne parvenait à se projeter suffisamment pour franchir le pas." },
      { type: "p", text: "C'est le risque avec les biens à rénover entièrement : ils demandent une vision que tout le monde n'a pas. Et sans vision, pas d'offre." },
      { type: "h3", text: "Les deux frères" },
      { type: "p", text: "Puis deux frères sont venus visiter." },
      { type: "p", text: "Ils ont vu le même appartement que tous les autres. Le même troisième étage, le même chantier en perspective, les mêmes contraintes. Mais ils ont vu autre chose aussi : une possibilité que personne avant eux n'avait identifiée." },
      { type: "p", text: "En repensant à la configuration des pièces, ils ont réalisé qu'on pouvait créer une troisième chambre. Transformer le T3 en T4. Ce n'était pas une idée que je leur avais soufflée - c'est la leur, entièrement. Et c'est ce qui fait toute la valeur de cette histoire." },
      { type: "p", text: "Ils ont fait le calcul : rénovation complète, création de la chambre supplémentaire, revente ou mise en location d'un T4 dans ce quartier. La rentabilité suivait. Ils ont fait une offre." },
      { type: "h3", text: "Ce que cette vente m'a appris" },
      { type: "p", text: "Mon rôle dans cette histoire n'a pas été de trouver l'idée. C'est eux qui l'ont eue, et je ne vais pas m'en attribuer le mérite." },
      { type: "p", text: "Mon rôle a été de continuer à présenter ce bien avec conviction pendant quatre mois, sans baisser le prix pour accélérer une vente qui n'aurait pas été la bonne. De croire qu'il existait quelque part deux acheteurs qui verraient ce que les autres ne voyaient pas. Et de leur laisser la place de le voir." },
      { type: "p", text: "Un bien à rénover ne cherche pas n'importe quel acheteur. Il cherche le bon. Celui qui a la vision, le projet, et l'appétit pour en faire quelque chose. Trouver cet acheteur-là prend parfois du temps. C'est normal. C'est même souvent nécessaire." },
      { type: "p", text: "Cette vente s'est bien terminée. Mieux que bien - c'est une belle aventure qui a commencé le jour de la signature." },
    ],
    cta: "Vous avez un bien atypique ou difficile à présenter ? Je reste à votre écoute.",
  },
  {
    slug: "primo-accedant-toulouse",
    title: "Primo-accédant à Toulouse : par où commencer vraiment",
    cat: "Acheter autrement",
    excerpt: "Guide pratique, ancrage local fort. Pour ne pas démarrer dans le brouillard.",
    img: IMG.tlseSaintSernin,
    date: "2026-03-20",
    readingTime: 6,
    blocks: [
      { type: "p", text: "Acheter pour la première fois, c'est entrer dans un monde dont personne ne vous a vraiment expliqué les règles. Vous avez regardé des annonces, peut-être visité quelques biens, et vous avez l'impression que ça devrait avancer - mais quelque chose coince sans que vous sachiez exactement quoi." },
      { type: "p", text: "Voici par où commencer vraiment." },
      { type: "h3", text: "D'abord l'enveloppe, avant tout le reste" },
      { type: "p", text: "C'est l'erreur que je vois le plus souvent : chercher avant de savoir ce qu'on peut réellement mettre. Pas par négligence - par enthousiasme. On a envie de voir, de se projeter, de toucher les murs. C'est humain." },
      { type: "p", text: "Mais visiter sans enveloppe calculée, c'est s'exposer à deux déceptions symétriques : tomber amoureux d'un bien hors de portée, ou passer à côté de biens accessibles parce qu'on s'est fixé une limite trop basse par prudence." },
      { type: "p", text: "L'enveloppe, c'est la première conversation à avoir - avec un courtier ou directement avec votre banque. Elle tient compte de vos revenus, de votre apport, de votre situation professionnelle, et de vos charges actuelles. C'est elle qui définit le terrain de jeu réel." },
      { type: "p", text: "Dans cette conversation, raisonnez en mensualité idéale autant qu'en montant maximum finançable. Ce que la banque accepte de vous prêter peut être plus élevé que ce avec quoi vous voulez vivre confortablement pendant vingt ans. Les dispositifs d'aide auxquels vous pouvez prétendre - PTZ, prêt Action Logement et autres - viendront naturellement dans cet échange. Ce sont votre banquier ou courtier les mieux placés pour les appliquer à votre situation." },
      { type: "h3", text: "Le bien parfait n'existe pas - et c'est une bonne nouvelle" },
      { type: "p", text: "C'est la deuxième chose que je dis à tous les primo-accédants : le bien parfait n'existe pas. Pas dans votre budget, pas à Toulouse, pas ailleurs. Ce qui existe, c'est le bien qui correspond à vos critères essentiels - et la capacité à faire la paix avec le reste." },
      { type: "p", text: "Avant de visiter quoi que ce soit, faites un exercice simple : listez ce qui est non négociable, et ce qui l'est." },
      { type: "p", text: "Le non négociable, c'est ce sans quoi vous ne pouvez pas vivre. Un quartier précis parce que vous travaillez à côté. Un minimum de surface parce que vous avez besoin d'un bureau. Un extérieur parce que vous avez un chien. Ces critères ne bougent pas." },
      { type: "p", text: "Le négociable, c'est tout le reste. L'étage, l'exposition, l'état de la cuisine, la présence d'une cave. Ces éléments comptent, mais ils peuvent être acceptés, compensés, ou améliorés avec le temps." },
      { type: "p", text: "Cette liste change tout. Elle vous évite de rejeter un bien pour une raison secondaire tout en passant à côté d'un bien qui coche tout ce qui compte vraiment." },
      { type: "h3", text: "Toulouse : où regarder selon votre profil" },
      { type: "p", text: "Toulouse est une ville qui se transforme rapidement, et les écarts de prix entre quartiers restent significatifs." },
      { type: "p", text: "En hypercentre, les prix sont élevés et les surfaces souvent contraintes. C'est un choix de mode de vie assumé - tout à pied, mais peu d'espace pour le prix." },
      { type: "p", text: "Plus on s'éloigne, plus la surface gagne - et plus la voiture devient nécessaire. C'est un arbitrage à faire consciemment, pas par défaut. Un acheteur citadin raisonnera proximité métro et commerces. Un acheteur autonome en voiture cherchera l'accès rapide à la rocade, une gare à proximité, une place de parking. Ce sont ces critères concrets qui sécurisent le quotidien et la revente." },
      { type: "h3", text: "Ce que j'apporte dans ce premier achat" },
      { type: "p", text: "Être accompagné pour un premier achat, ce n'est pas un luxe. C'est éviter les erreurs que personne ne vous dit à l'avance - les charges de copropriété sous-estimées, le DPE qui complique le financement, le quartier qui semblait bien sur le papier et qui ne correspond pas à votre quotidien." },
      { type: "p", text: "Mon rôle est de structurer votre projet avant même la première visite, de vous aider à poser les bons critères, et de vous présenter des biens qui correspondent vraiment à ce que vous cherchez. Pas de vous faire visiter pour visiter." },
    ],
    cta: "Vous achetez pour la première fois et vous ne savez pas par où commencer ? Je reste à votre écoute.",
  },
  {
    slug: "renover-avant-de-vendre",
    title: "Faut-il rénover avant de vendre ? Ce que je dis à mes clients",
    cat: "Vendre à Toulouse",
    excerpt: "Quand ça change le prix, quand ça ne change rien. Point de vue assumé.",
    img: IMG.blogCuisine,
    date: "2026-03-13",
    readingTime: 5,
    blocks: [
      { type: "p", text: "C'est une des premières questions que se posent les vendeurs. Et c'est une bonne question - parce que la réponse engage parfois plusieurs milliers d'euros et des semaines de travaux avant même que le bien soit sur le marché." },
      { type: "p", text: "Ma position est claire, et je la dis d'emblée : dans la grande majorité des cas, non. Mieux vaut ne pas rénover avant de vendre." },
      { type: "h3", text: "Pourquoi l'argent investi revient rarement" },
      { type: "p", text: "L'idée est séduisante : refaire la cuisine, repeindre les murs, moderniser la salle de bain - et récupérer la mise au moment de la vente, voire vendre plus cher. En pratique, c'est rarement ce qui se passe." },
      { type: "p", text: "L'acheteur valorise les travaux que vous avez faits à sa façon, pas à la vôtre. Il voit une cuisine refaite - mais pas forcément celle qu'il aurait choisie. Il voit des murs repeints - dans une couleur qu'il va peut-être changer dans six mois. Vous avez dépensé, il tient compte de la présence des travaux, rarement de leur coût réel." },
      { type: "p", text: "Et puis il y a la question des goûts. Cibler juste en matière d'esthétique est un exercice périlleux. Ce qui vous semble neutre et moderne peut sembler froid à un acheteur, ou daté à un autre. Les goûts et les couleurs, c'est précisément ce qu'on ne peut pas anticiper pour quelqu'un qu'on ne connaît pas encore." },
      { type: "h3", text: "Ce qu'il faut faire en revanche" },
      { type: "p", text: "Il y a une frontière claire entre rénover et soigner. Rénover, c'est transformer. Soigner, c'est présenter." },
      { type: "p", text: "Soigner le bien avant une vente, ça veut dire : réparer ce qui fuit, ce qui grince, ce qui clignote. Reboucher les trous dans les murs. Remplacer un joint décollé, une poignée cassée, un volet qui force. Ce sont des détails qui ne coûtent presque rien - mais qui, s'ils restent visibles, créent des questions dans l'esprit de l'acheteur." },
      { type: "p", text: "Or dans l'immobilier, comme ailleurs, quand il y a un doute, il n'y a plus de doute. Un robinet qui goutte, une fissure non expliquée, une porte qui ferme mal - chacun de ces détails ouvre une interrogation. L'acheteur commence à se demander ce qu'il ne voit pas. Et cette méfiance est bien plus coûteuse que le prix de la réparation." },
      { type: "h3", text: "L'exception : quand les travaux sont vraiment trop lourds à porter" },
      { type: "p", text: "Il y a des situations où le bien est dans un état qui risque de bloquer la vente ou d'effrayer tous les acheteurs. Une installation électrique aux normes des années 70, une toiture qui demande une intervention urgente, une salle de bain hors d'usage." },
      { type: "p", text: "Dans ces cas, deux options se posent : soit on vend tel quel, en ajustant le prix pour tenir compte des travaux à venir - et l'acheteur les fait lui-même, à son goût, avec ses artisans. Soit on engage les travaux indispensables pour rendre le bien habitable sans inquiétude immédiate." },
      { type: "p", text: "Ce choix dépend du profil des acheteurs que le bien va attirer, du secteur, et du budget du vendeur. C'est une conversation qu'on a ensemble, avec les chiffres sur la table." },
      { type: "p", text: "Ce que je déconseille systématiquement : les rénovations esthétiques importantes décidées seul, sans avoir estimé le bien d'abord. Rénover avant de savoir à quel prix vous allez vendre, c'est prendre un risque financier sans filet." },
      { type: "h3", text: "L'ordre que je recommande toujours" },
      { type: "p", text: "D'abord l'estimation. Ensuite la conversation sur les travaux, si nécessaire. Jamais l'inverse." },
      { type: "p", text: "Parce que le prix de vente conditionne tout le reste. Et parce que réparer ce qui doit l'être coûte bien moins cher que rénover pour des acheteurs qu'on n'a pas encore rencontrés." },
    ],
    cta: "Vous vous posez cette question pour votre bien ? Je reste à votre écoute.",
  },
  {
    slug: "promesse-de-vente-clauses",
    title: "Comprendre la promesse de vente : les clauses qui protègent le vendeur",
    cat: "Vendre à Toulouse",
    excerpt: "La promesse n'est pas une formalité. C'est le moment où tout se joue vraiment.",
    img: IMG.tlseHotelParticulier,
    date: "2026-03-06",
    readingTime: 6,
    blocks: [
      { type: "p", text: "La promesse de vente est souvent perçue comme une étape intermédiaire, une formalité avant la « vraie » signature. C'est une erreur de perception, et c'est peut-être la plus coûteuse qu'on puisse faire dans une transaction immobilière." },
      { type: "p", text: "C'est là que tout se dit. C'est le moment le plus long et le plus important de la vente. La signature de l'acte définitif chez le notaire n'en est que la validation finale, la confirmation de ce qui a été posé lors de la promesse. Toutes les questions doivent être posées ici. Toutes les règles pour la suite sont fixées ici. C'est ce premier acte qui conditionne la bonne fin de la vente." },
      { type: "h3", text: "Chez le notaire, pas en agence" },
      { type: "p", text: "Je suis favorable à signer la promesse de vente chez le notaire, pas en agence. Même si certaines agences disposent de services juridiques compétents, le notaire reste votre allié naturel dans cette démarche." },
      { type: "p", text: "C'est lui qui vous connaît. C'est lui qui vous a peut-être accompagné sur un premier achat, qui connaît votre situation patrimoniale, votre famille, vos projets. C'est lui qui vous accompagnera sur les suivants. Un notaire n'est pas un prestataire ponctuel, c'est un partenaire de long terme. Autant l'impliquer dès le premier acte, là où tout se joue." },
      { type: "h3", text: "Ce que la promesse engage vraiment" },
      { type: "p", text: "Dès la signature, les deux parties sont engagées. L'acheteur dispose d'un délai de rétractation de dix jours, c'est la loi et c'est légitime. Passé ce délai, une décision immobilière n'est pas un caprice. Elle se prend après réflexion, avec toutes les informations nécessaires, et elle engage pleinement." },
      { type: "p", text: "Au-delà du séquestre versé à la signature, le notaire demande généralement 500 euros d'avance sur frais pour couvrir les premières démarches administratives engagées. Ces frais ne sont pas récupérables en cas de désistement. C'est normal. On s'engage, et cet engagement a un coût dès le premier jour." },
      { type: "h3", text: "La clause suspensive de financement, une protection sérieuse" },
      { type: "p", text: "C'est la clause la plus courante, et la plus mal comprise." },
      { type: "p", text: "Elle protège l'acheteur en cas de refus de prêt bancaire avéré. Deux refus de deux établissements différents sont généralement requis pour qu'elle joue. Et c'est là que je veux être claire : on ne joue pas avec les interlocuteurs financiers." },
      { type: "p", text: "Une banque ne va pas s'amuser à monter un dossier complet, mobiliser ses équipes, instruire une demande de prêt, pour finalement rédiger un refus de complaisance afin de permettre à un acheteur de se désengager proprement. Ce n'est pas ainsi que ça fonctionne, et ce n'est pas ainsi qu'on se respecte mutuellement." },
      { type: "p", text: "On croit en son projet, et on va jusqu'au bout. Cela suppose d'avoir consulté en amont un établissement bancaire ou un courtier qui, sur la base d'une simulation sérieuse, aura donné un premier feu vert avant même que la promesse soit signée. Tant qu'un dossier n'est pas examiné et validé par la commission risque, une part d'incertitude réelle demeure - c'est vrai. Mais cette incertitude se gère en préparant sérieusement, pas en se ménageant une sortie de secours." },
      { type: "p", text: "Ce qui protège le vendeur, c'est la précision des conditions inscrites dans cette clause : le montant emprunté, le taux maximum, la durée. Des paramètres cohérents avec le projet réel de l'acheteur, pas une clause rédigée trop largement qui laisse une porte ouverte à tout." },
      { type: "h3", text: "Le respect du timing, une responsabilité partagée" },
      { type: "p", text: "La promesse de vente fixe des dates. Ces dates ne sont pas indicatives, elles sont contractuelles." },
      { type: "p", text: "Les délais passent très vite. On ne maîtrise pas toute la chaîne des intervenants - banque, notaire, diagnostiqueurs, syndic de copropriété. Tout doit se mettre en mouvement sans tarder dès la signature de la promesse, précisément pour ne pas se retrouver dans le stress des dernières lignes droites." },
      { type: "p", text: "Pour le vendeur, c'est une protection contre une situation qui s'étire sans raison. Pour l'acheteur, c'est une incitation à finaliser son financement sans attendre. Pour les deux, c'est le cadre qui permet à la vente de se conclure sereinement." },
      { type: "h3", text: "Ce que j'en retiens pour mes vendeurs" },
      { type: "p", text: "Une promesse de vente bien rédigée, signée chez le notaire, avec des clauses précises et des délais clairs, est la première protection du vendeur. Ce n'est pas un document qu'on parcourt rapidement avant de signer." },
      { type: "p", text: "Mon rôle est de m'assurer que ce moment est abordé avec le sérieux qu'il mérite. Que toutes les questions ont été posées. Que chaque partie comprend ce à quoi elle s'engage. Et que la vente qui commence à la promesse a toutes les chances de se terminer bien chez le notaire." },
      { type: "p", text: "La deuxième signature n'est qu'une confirmation. C'est la première qui compte." },
    ],
    cta: "Vous avez une question sur le déroulé d'une vente ? Je reste à votre écoute.",
  },
  {
    slug: "artisans-de-confiance-toulouse",
    title: "Les artisans en qui j'ai confiance - et pourquoi je vous les recommande",
    cat: "Vendre / Acheter",
    excerpt: "Un réseau construit ventes après ventes, sans commission ni hasard.",
    img: IMG.tlseEscalier,
    date: "2026-02-27",
    readingTime: 4,
    blocks: [
      { type: "p", text: "Il y a une question que mes clients me posent souvent, une fois la vente signée ou le projet d'achat lancé : « Est-ce que vous connaissez quelqu'un de bien pour les travaux ? »" },
      { type: "p", text: "La réponse est oui. Et ce n'est pas anodin." },
      { type: "h3", text: "Ce que « quelqu'un de bien » veut dire" },
      { type: "p", text: "Trouver un artisan fiable est un vrai sujet. Pas parce que les bons artisans n'existent pas - ils existent, et ils sont nombreux. Mais parce que les trouver sans réseau, sans recommandation, sans avoir déjà travaillé avec eux, c'est un exercice qui prend du temps et qui comporte une part de risque." },
      { type: "p", text: "Un devis qui tarde. Des travaux qui s'étirent. Une finition bâclée. Ce sont des situations que tout le monde a vécues ou entendues. Et quand on vient d'acheter un bien, qu'on est déjà mobilisé sur le financement et l'emménagement, ce n'est pas le moment d'essuyer ces déconvenues." },
      { type: "p", text: "C'est pour ça que j'ai constitué, au fil de mes ventes, un réseau d'artisans et de professionnels du bâtiment en qui j'ai confiance. Tous corps de métier : plomberie, électricité, maçonnerie, peinture, menuiserie - selon les besoins." },
      { type: "h3", text: "Une sélection par l'expérience, pas par le hasard" },
      { type: "p", text: "Je ne recommande personne que je n'ai pas vu travailler. Ces professionnels, je les ai rencontrés sur des ventes. J'ai vu comment ils interviennent, comment ils communiquent, comment ils tiennent leurs délais et leurs devis. C'est comme ça que la confiance se construit - pas sur une carte de visite, sur des actes." },
      { type: "p", text: "Ce réseau s'est constitué naturellement, dans la même logique que mon activité : le bouche-à-oreille, la recommandation, la reconnaissance du travail bien fait. Je travaille moi-même essentiellement sur recommandation. C'est une façon d'exercer qui engage - et qui oblige à ne recommander que ce qu'on cautionnerait pour soi-même." },
      { type: "h3", text: "À qui je m'adresse principalement" },
      { type: "p", text: "Cette ressource est particulièrement utile pour les acheteurs. Acheter un bien avec des travaux à prévoir, c'est souvent une bonne opération - à condition de savoir ce que ces travaux vont réellement coûter, et de pouvoir les confier à quelqu'un de sérieux rapidement." },
      { type: "p", text: "Avant même la signature du compromis, je peux organiser un passage d'artisan pour estimer les travaux envisagés. Pas pour décider à votre place - pour que vous ayez les chiffres réels en main au moment où vous en avez besoin." },
      { type: "p", text: "Pour les vendeurs, c'est utile dans la logique de ce qu'on a vu précédemment : soigner le bien sans sur-investir. Réparer ce qui doit l'être, avec les bonnes personnes, au bon prix." },
      { type: "h3", text: "Ce qui m'anime là-dedans" },
      { type: "p", text: "Je ne touche aucune commission sur ces recommandations. Ce n'est pas un service commercial - c'est une extension naturelle de mon accompagnement." },
      { type: "p", text: "Ce qui m'anime, c'est le souci du travail bien fait. Recommander quelqu'un de confiance, c'est prolonger l'engagement que j'ai pris envers mon client au-delà de la signature. Et quand un artisan que j'ai recommandé fait du bon travail, et que le client me le dit - c'est la même satisfaction que quand une vente se conclut bien." },
      { type: "p", text: "Je travaille sur recommandation, je recommande avec le même soin. C'est un cercle qui n'a de valeur que si chaque maillon tient." },
    ],
    cta: "Vous avez un projet et cherchez des professionnels fiables ? Je reste à votre écoute.",
  },
  {
    slug: "ce-quon-achete-vraiment",
    title: "Ce qu'on achète vraiment - ma philosophie d'accompagnement",
    cat: "Acheter autrement",
    excerpt: "Un bon achat, c'est un achat qui laisse des portes ouvertes.",
    img: IMG.helenCanape,
    date: "2026-02-20",
    readingTime: 5,
    blocks: [
      { type: "p", text: "Quand un acheteur me contacte, il a souvent déjà une image en tête. Un bien, un quartier, une vie qui commence. Cette excitation, je la respecte. Elle est le moteur du projet." },
      { type: "p", text: "Mon rôle n'est pas de la tempérer. C'est de l'accompagner pour qu'elle dure - bien après la signature." },
      { type: "h3", text: "Qu'est-ce qu'on achète vraiment ?" },
      { type: "p", text: "La question peut sembler évidente. Un appartement, une maison, des mètres carrés. Mais derrière l'achat immobilier, il y a toujours un projet de vie - et les projets de vie bougent." },
      { type: "p", text: "Une séparation. Une mutation professionnelle. Un enfant qui arrive, ou qui part. Un parent à accompagner. La vie est pleine de surprises, et c'est tant mieux. Mais ces surprises ont des conséquences sur un bien immobilier qu'on pensait garder dix ans et qu'on doit revendre au bout de trois." },
      { type: "p", text: "C'est pourquoi je pose toujours cette question tôt dans notre conversation : qu'est-ce que vous achetez, et pour combien de temps ? Pas pour freiner l'élan - pour s'assurer que le bien choisi résiste aux imprévus. Si demain la situation change, quelles sont les options ? Le bien peut-il se louer facilement ? Se revendre sans difficulté ? Accueillir une configuration familiale différente ?" },
      { type: "p", text: "Un bon achat, c'est un achat qui laisse des portes ouvertes." },
      { type: "h3", text: "Le coup de cœur - ami ou ennemi ?" },
      { type: "p", text: "Le coup de cœur existe. Il est réel, il est puissant, et il n'est pas un problème en soi. Le problème, c'est quand il efface tout le reste." },
      { type: "p", text: "Certains biens sont magnifiques et très particuliers. Une configuration atypique, des matériaux rares, une décoration très affirmée. Ils séduisent immédiatement - et pour les mêmes raisons, ils ne séduiront qu'un acheteur sur cent au moment de la revente." },
      { type: "p", text: "Une niche trop restrictive se revend mal, ou lentement, ou en dessous de ce qu'on espérait. Je ne dis pas d'ignorer le coup de cœur. Je dis de le regarder avec cette question en tête : est-ce que ce qui me séduit aujourd'hui séduira quelqu'un d'autre demain ? Si la réponse est oui, foncez. Si elle est incertaine, on en parle." },
      { type: "h3", text: "Les travaux - pour qui, pour quoi ?" },
      { type: "p", text: "Rafraîchir un bien pour y vivre mieux, c'est légitime et souvent peu coûteux. Repeindre, changer un revêtement de sol, moderniser une salle de bain - ce sont des décisions de confort personnel. Faites-les pour vous, pas pour la revente." },
      { type: "p", text: "Parce que les matériaux et les choix esthétiques que vous faites ne seront pas nécessairement récupérables au moment de vendre. Ce que vous trouvez beau, élégant, moderne - un futur acheteur peut le trouver daté ou ne pas s'y projeter. C'est toujours cette histoire de goûts et de couleurs qu'on ne peut pas anticiper pour quelqu'un qu'on ne connaît pas encore." },
      { type: "p", text: "Le standing aussi a ses limites. Sur-investir dans des matériaux premium dans un bien d'un standing moyen, dans un quartier dont les prix plafonnent, c'est prendre le risque de ne jamais récupérer la mise. Le marché a ses propres règles de cohérence - et il les applique indépendamment de ce que les travaux vous ont coûté." },
      { type: "p", text: "La bonne question avant tout chantier : est-ce pour mon confort, ou pour la valeur ? Les deux peuvent se rejoindre - mais pas toujours." },
      { type: "h3", text: "Calibrer son investissement - anticiper le grain de sable" },
      { type: "p", text: "Acheter, c'est aussi se projeter sur la revente. Pas avec pessimisme - avec lucidité." },
      { type: "p", text: "Combien de temps vais-je garder ce bien dans le scénario le plus probable ? Et dans un scénario imprévu ? Est-ce que le bien que j'achète aujourd'hui correspond à ce que le marché recherchera dans cinq ou dix ans ? Est-ce que mon investissement est calibré au bon niveau pour ce secteur, ce type de bien, ce profil d'acheteur futur ?" },
      { type: "p", text: "Ces questions ne tuent pas le rêve. Elles le solidifient." },
      { type: "p", text: "Un achat immobilier bien pensé, c'est un achat dans lequel on entre avec enthousiasme et qu'on peut quitter sereinement si la vie le demande. C'est un projet qui reste une ressource, pas une contrainte." },
      { type: "h3", text: "Ce que j'apporte dans cette réflexion" },
      { type: "p", text: "Je ne suis pas là pour tempérer l'excitation du projet. Je suis là pour l'accompagner - pour que le bien choisi tienne ses promesses dans la durée, que la vie suive le plan prévu ou pas." },
      { type: "p", text: "Mon rôle, c'est de poser les bonnes questions au bon moment. Pas pour freiner - pour que le rêve brille plus longtemps." },
    ],
    cta: "Vous avez un projet d'achat et envie d'en parler sérieusement ? Je reste à votre écoute.",
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}
