/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendeursRouteImport } from './routes/vendeurs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EstimationRouteImport } from './routes/estimation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcheteursRouteImport } from './routes/acheteurs'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const VendeursRoute = VendeursRouteImport.update({
  id: '/vendeurs',
  path: '/vendeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimationRoute = EstimationRouteImport.update({
  id: '/estimation',
  path: '/estimation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcheteursRoute = AcheteursRouteImport.update({
  id: '/acheteurs',
  path: '/acheteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/acheteurs': typeof AcheteursRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/estimation': typeof EstimationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendeurs': typeof VendeursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/acheteurs': typeof AcheteursRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/estimation': typeof EstimationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendeurs': typeof VendeursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/acheteurs': typeof AcheteursRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/estimation': typeof EstimationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendeurs': typeof VendeursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/acheteurs'
    | '/blog'
    | '/contact'
    | '/estimation'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/vendeurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/acheteurs'
    | '/blog'
    | '/contact'
    | '/estimation'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/vendeurs'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/acheteurs'
    | '/blog'
    | '/contact'
    | '/estimation'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/vendeurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AcheteursRoute: typeof AcheteursRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EstimationRoute: typeof EstimationRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendeursRoute: typeof VendeursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendeurs': {
      id: '/vendeurs'
      path: '/vendeurs'
      fullPath: '/vendeurs'
      preLoaderRoute: typeof VendeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimation': {
      id: '/estimation'
      path: '/estimation'
      fullPath: '/estimation'
      preLoaderRoute: typeof EstimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheteurs': {
      id: '/acheteurs'
      path: '/acheteurs'
      fullPath: '/acheteurs'
      preLoaderRoute: typeof AcheteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AcheteursRoute: AcheteursRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EstimationRoute: EstimationRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendeursRoute: VendeursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
